# Dockerfile.dev
FROM golang:1.25

WORKDIR /app

# Install Air (auto-reload)
RUN go install github.com/air-verse/air@latest

# Copy dependencies & download
COPY go.mod go.sum ./
RUN go mod download

# Copy source code
COPY . .

# Expose port
EXPOSE 8080

# Jalankan Air untuk development
CMD ["air", "-c", ".air.toml"]